[chores] Addressed review feedback

diff --git a/runbuild b/runbuild
--- a/runbuild
+++ b/runbuild
@@ -11,7 +11,6 @@ BUILD_DIR=${BUILD_DIR-$(pwd)/build}
 DOWNLOADS_DIR=${DOWNLOADS_DIR-$(pwd)/downloads}
 START_TIME=${START_TIME-$(date +"%Y-%m-%d-%H%M%S")}
 VERSIONED_DIR="$DOWNLOADS_DIR/$START_TIME"
-COMPILE_TARGET=${COMPILE_TARGET-mips_24kc}
 LATEST_LINK="$DOWNLOADS_DIR/latest"
 CORES=${CORES:-$(nproc)}
 CURRENT_DIR=$(pwd)
@@ -52,6 +51,11 @@ sed -i '/routing/d' feeds.conf
 	echo "CONFIG_PACKAGE_openwisp-monitoring=y"
 } >>.config
 make defconfig
+COMPILE_TARGET=${COMPILE_TARGET:-$(grep '^CONFIG_TARGET_ARCH_PACKAGES=' .config | cut -d '"' -f 2)}
+if [ -z "$COMPILE_TARGET" ]; then
+	echo "ERROR: OpenWrt package architecture not found in .config"
+	exit 1
+fi
 
 if [ ! "$CI_CACHE" ]; then
 	make -j"$CORES" tools/install
