[feature] Add random delay before send_data
This can help prevent server overload.

Signed-off-by: Nguyen Quang Minh <hello@minhng99.eu>

diff --git a/openwisp-monitoring/files/monitoring.init b/openwisp-monitoring/files/monitoring.init
--- a/openwisp-monitoring/files/monitoring.init
+++ b/openwisp-monitoring/files/monitoring.init
@@ -50,6 +50,7 @@ start_service() {
 	config_load openwisp-monitoring
 	config_get monitored_interfaces monitoring monitored_interfaces "*"
 	config_get interval monitoring interval "300"
+	config_get send_delay monitoring send_delay "10"
 	config_get_bool verbose_mode monitoring verbose_mode "0"
 	config_get required_memory monitoring required_memory "0.05"
 	config_get max_retries monitoring max_retries "5"
@@ -61,7 +62,15 @@ start_service() {
 			-p daemon.err
 		exit 1
 	fi
+	send_delay="$(time_to_seconds "$send_delay")"
+	if [ "$send_delay" -lt 1 ]; then
+		logger -s "send_delay is invalid. Use time value(eg: '10', '2m', '3h', '1d')" \
+			-t openwisp-monitoring \
+			-p daemon.err
+		exit 1
+	fi
 	interval="--interval $interval"
+	send_delay="--send_delay $send_delay"
 	verbose="--verbose_mode ${verbose_mode:-0}"
 	required_memory="--required_memory $required_memory"
 	max_retries="--max_retries $max_retries"
@@ -75,7 +84,7 @@ start_service() {
 
 	procd_open_instance "openwisp-monitoring_send_data"
 	# shellcheck disable=SC2086
-	procd_set_param command $PROG $base_url $uuid $key $verify_ssl $interval $verbose $max_retries --mode send
+	procd_set_param command $PROG $base_url $uuid $key $verify_ssl $interval $send_delay $verbose $max_retries --mode send
 	procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
 	[ "$verbose_mode" -eq "1" ] && procd_set_param stdout 1 && procd_set_param stderr 1
 	procd_close_instance
