[enhancement] Move logger calls in subroutine #57
Closes #57

diff --git a/openwisp-monitoring/files/monitoring.init b/openwisp-monitoring/files/monitoring.init
--- a/openwisp-monitoring/files/monitoring.init
+++ b/openwisp-monitoring/files/monitoring.init
@@ -56,12 +56,8 @@ start_service() {
 	config_get bootup_delay monitoring bootup_delay "10"
 
 	interval="$(time_to_seconds "$interval")"
-	if [ "$interval" -lt 1 ]; then
-		logger -s "Interval is invalid. Use time value(eg: '10', '2m', '3h', '1d')" \
-			-t openwisp-monitoring \
-			-p daemon.err
-		exit 1
-	fi
+	[ -z "$interval" ] && { echo "Interval is invalid. Use time value(eg: '10', '2m', '3h', '1d')" 1>&2 && exit 1; }
+
 	interval="--interval $interval"
 	verbose="--verbose_mode ${verbose_mode:-0}"
 	required_memory="--required_memory $required_memory"
@@ -72,25 +68,19 @@ start_service() {
 	# shellcheck disable=SC2086,SC2154
 	procd_set_param command $PROG $interval $verbose $required_memory --mode collect --monitored_interfaces "$monitored_interfaces"
 	procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
-	[ "$verbose_mode" -eq "1" ] && procd_set_param stdout 1 && procd_set_param stderr 1
 	procd_close_instance
 
 	procd_open_instance "openwisp-monitoring_send_data"
 	# shellcheck disable=SC2086
 	procd_set_param command $PROG $base_url $uuid $key $verify_ssl $interval $verbose $max_retries $bootup_delay --mode send
 	procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry:-5}"
-	[ "$verbose_mode" -eq "1" ] && procd_set_param stdout 1 && procd_set_param stderr 1
 	procd_close_instance
 
-	logger -s "$PROG_NAME started" \
-		-t openwisp-monitoring \
-		-p daemon.info
+	logger -s "$PROG_NAME started" -t openwisp-monitoring -p daemon.info
 }
 
 stop_service() {
-	logger -s "$PROG_NAME stopping" \
-		-t openwisp-monitoring \
-		-p daemon.info
+	logger -s "$PROG_NAME stopping" -t openwisp-monitoring -p daemon.info
 }
 
 service_triggers() {
